spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crypto_system?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
